config/routes.rb
Rails.application.routes.draw do
  devise_for :companies, controllers: {
    registrations: 'companies/registrations',
    sessions: 'companies/sessions'
  }
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get 'question', to: 'pages#question'
  root to: 'pages#home'
  get 'profile', to: 'pages#profile'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/company.rb
class Company < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_one_attached :photo
  validates :company_name, presence: true

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_one_attached :photo
  validates :role, presence: true

  enum role: { Star: 'Star', Angel: 'Angel', Company: 'Company' }

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[first_name last_name photo role professional_position])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: %i[first_name last_name photo role professional_position])
  end
end

app/controllers/companies/confirmations_controller.rb
# frozen_string_literal: true

class Companies::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/companies/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Companies::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/companies/passwords_controller.rb
# frozen_string_literal: true

class Companies::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/companies/registrations_controller.rb
# frozen_string_literal: true

class Companies::RegistrationsController < Devise::RegistrationsController
  private

  def sign_up_params
    params.require(:company).permit(:email, :password, :password_confirmation, :photo, :company_name)
  end
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/companies/sessions_controller.rb
# frozen_string_literal: true

class Companies::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/companies/unlocks_controller.rb
# frozen_string_literal: true

class Companies::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
    @angels = User.where(role: "Angel")
    @companies = Company.all
  end

  def profile
  end

  def question
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/companies/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/companies/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Star</title>
    <link rel="icon" href="https://res.cloudinary.com/ddfjqexgw/image/upload/v1699796920/starin-symbol-full-color-version-rgb-29.9861in_300ppi_hsusn0.png" type="image/x-icon">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <%= render "shared/navbar" %>
    <%= yield %>
    <%= render "shared/navbar_bottom" %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="container homepage-container mt-5">
  <div class="block-homepage d-flex">
    <div class="titleblock">
      <p class="text-light">Empowering Dreams: Connecting Brazilian Talent with German Opportunities. Join our platform where dedicated volunteers (Angels) mentor aspiring stars (Candidates) to bridge the gap of skilled professionals in Germany.</p>
      <p class="text-light">Let's shape the future together!</p>
      <div class="buttons mt-5">
        <% if current_user | current_company %>
        <% else %>
          <%= link_to "Get Started", new_user_registration_path, class:"btn btn-primary" %>
          <%#= link_to "Get Started as a Company", new_company_registration_path, class:"btn btn-primary mx-2" %>
        <% end %>
      </div>
    </div>
    <div>
      <img class="image-homepage" src="https://res.cloudinary.com/ddfjqexgw/image/upload/v1699898731/homepage-image-animated_zg2g4h.png" width="400" height="400" alt="Your Image Description">
    </div>
  </div>
  <h1 class="text-light text-center my-5">Our Angels</h1>
  <div class="cards mb-5">
    <% @angels.each do |angel| %>
      <div class="card-product mx-2">
        <%= cl_image_tag angel.photo.key %>
        <div class="card-product-infos">
          <h2><%= angel.first_name %> <%= angel.last_name %></h2>
          <p><%= angel.professional_position %></p>
        </div>
      </div>
    <% end %>
  </div>
  <h1 class="text-light text-center my-5">Companies</h1>
  <div class="cards mb-5">
    <% @companies.each do |company| %>
      <div class="card-product mx-2">
        <%= cl_image_tag company.photo.key %>
        <div class="card-product-infos">
          <h2><%= company.company_name %>
        </div>
      </div>
    <% end %>
  </div>
  <h1 class="text-light text-center my-5">Why you should get registered</h1>
  <div class="cards d-flex flex-row justify-content-center mb-5">
    <div class="card-wysgr mx-2">
      <img src="https://res.cloudinary.com/ddfjqexgw/image/upload/v1704882543/Star/Homepage/correct_jewrle.png" width="50" height="50" alt="correct tick" class="top-image">
      <h2 class="mt-4">Stars</h2>
      <div class="card-wysgr-infos">
        <strong><p>Because you need advices from who already made it.</p></strong>
      </div>
    </div>
    <div class="card-wysgr mx-2">
      <img src="https://res.cloudinary.com/ddfjqexgw/image/upload/v1704882543/Star/Homepage/correct_jewrle.png" width="50" height="50" alt="correct tick" class="top-image">
      <h2 class="mt-4">Stars</h2>
      <div class="card-wysgr-infos">
        <strong><p>Your career plan is personal and unique, you need personalized guidance.</p></strong>
      </div>
    </div>
    <div class="card-wysgr mx-2">
      <img src="https://res.cloudinary.com/ddfjqexgw/image/upload/v1704882543/Star/Homepage/correct_jewrle.png" width="50" height="50" alt="correct tick" class="top-image">
      <h2 class="mt-4">Angels</h2>
      <div class="card-wysgr-infos">
        <strong><p>You want to improve your interpersonal skills in a pratical way for free.</p></strong>
      </div>
    </div>
    <div class="card-wysgr mx-2">
      <img src="https://res.cloudinary.com/ddfjqexgw/image/upload/v1704882543/Star/Homepage/correct_jewrle.png" width="50" height="50" alt="correct tick" class="top-image">
      <h2 class="mt-4">Angels</h2>
      <div class="card-wysgr-infos">
        <strong><p>You want to make a social impact.</p></strong>
      </div>
    </div>
    <div class="card-wysgr mx-2">
      <img src="https://res.cloudinary.com/ddfjqexgw/image/upload/v1704882543/Star/Homepage/correct_jewrle.png" width="50" height="50" alt="correct tick" class="top-image">
      <h2 class="mt-4">Clouds</h2>
      <div class="card-wysgr-infos">
        <strong><p>You want to boost your recruiting process.</p></strong>
      </div>
    </div>
    <div class="card-wysgr mx-2">
      <img src="https://res.cloudinary.com/ddfjqexgw/image/upload/v1704882543/Star/Homepage/correct_jewrle.png" width="50" height="50" alt="correct tick" class="top-image">
      <h2 class="mt-4">Clouds</h2>
      <div class="card-wysgr-infos">
        <strong><p>You want to increase diversity in your company.</p></strong>
      </div>
    </div>
  </div>
</div>

app/views/pages/profile.html.erb
<% if user_signed_in? %>
  <h2 class="text-light">Profile Page</h2>
  <div class="d-flex">
    <%= cl_image_tag current_user.photo.key, crop: :fill, class:"profile-picture", alt: "profile picture" %>
    <div class="data mx-5">
      <h4 class="text-light"><%= current_user.first_name %> <%= current_user.last_name %></h4>
      <h5 class="text-light"><%= current_user.role %></h5>
    </div>
  </div>
<% elsif company_signed_in? %>
  <h2 class="text-light">Company Page</h2>
    <div class="d-flex">
      <%= cl_image_tag current_company.photo.key, crop: :fill, class:"profile-picture", alt: "company picture" %>
      <div class="data mx-5">
        <h4 class="text-light"><%= current_company.company_name %></h4>
      </div>
    </div>
<% end %>

app/views/pages/question.html.erb
<div class="d-flex justify-content-center">
  <%= link_to new_user_session_path, class:"card btn question-card mx-5" do %>
    <h2> Star / Angel</h2>
    <%= image_tag "https://res.cloudinary.com/ddfjqexgw/image/upload/v1704825289/Star/Homepage/star_and_angel_a8vrof.png" %>
  <% end %>
  <%= link_to new_company_session_path, class:"card btn question-card" do %>
    <h2> Company</h2>
    <%= image_tag "https://res.cloudinary.com/ddfjqexgw/image/upload/v1704825568/Star/Homepage/company_uctgsa.png" %>
  <% end %>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand m-2" do %>
      <%= image_tag "https://res.cloudinary.com/ddfjqexgw/image/upload/v1699906527/starin-complete-logo-inverted-color-version-rgb-29.9861in_300ppi_pm4s9h.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", root_path, class: "btn btn-primary nav-link text-light mx-2" %>
          </li>
          <li class="nav-item">
            <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "btn btn-primary nav-link text-light mx-2" %>
          </li>
          <li class="nav-item">
            <%= link_to profile_path do %>
              <%= cl_image_tag current_user.photo.key, crop: :fill, class: "avatar", alt: "profile picture" %>
            <% end %>
          </li>
          <% elsif company_signed_in? %>
            <li class="nav-item">
              <%= link_to "Home", root_path, class: "btn btn-primary nav-link text-light mx-2" %>
            </li>
            <li class="nav-item">
              <%= link_to "Log out", destroy_company_session_path, data: { turbo_method: :delete }, class: "btn btn-primary nav-link text-light mx-2" %>
            </li>
            <li class="nav-item">
              <%= link_to profile_path do %>
                <%= cl_image_tag current_company.photo.key, crop: :fill, class: "avatar", alt: "company picture" %>
              <% end %>
            </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", question_path, class: "btn btn-primary text-light" %>
            <%#= link_to "Login as a Company", new_company_session_path, class: "btn btn-primary text-light mx-2" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_navbar_bottom.html.erb
<div class="bottom-navbar">
  <div>
    <p>Cookie Policy Imprint Privacy Policy</p>
    </p>© 2023 Starin All rights reserved.</p>
  </div>
  <div>
    <img src="https://res.cloudinary.com/ddfjqexgw/image/upload/v1704885676/Star/Homepage/instagram_dhauox.png" width="40" height="40" alt="instagram icon" class="mx-2">
    <img src="https://res.cloudinary.com/ddfjqexgw/image/upload/v1704885676/Star/Homepage/youtube_oi8zzz.png" width="40" height="40" alt="youtube icon" class="mx-2">
    <img src="https://res.cloudinary.com/ddfjqexgw/image/upload/v1704885676/Star/Homepage/linkedin_kef1im.png" width="40" height="40" alt="linkedin icon" class="mx-2">
  </div>
</div>